CREATE TABLE MORADOR (
	ID NUMERIC(8) NOT NULL,
	ID_PESSOA NUMERIC(8) NOT NULL,
	ID_UNIDADE NUMERIC(8) NOT NULL,
	
	CONSTRAINT PK_MORADOR PRIMARY KEY(ID),
	CONSTRAINT FK_MORADOR_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID),
	CONSTRAINT FK_MORADOR_UNIDADE FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE (ID)
);

CREATE SEQUENCE SEQ_MORADOR;
