CREATE TABLE PERFIL (
	ID NUMERIC(8) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
	CONSTRAINT PK_PERFIL PRIMARY KEY (ID)
);

CREATE TABLE USUARIO (
	ID NUMERIC(8) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL,
	SENHA VARCHAR(200) NOT NULL,
	ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
	ID_PERFIL NUMERIC(8) NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
	CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL (ID)
);

CREATE SEQUENCE SEQ_PERFIL;
CREATE SEQUENCE SEQ_USUARIO;
