CREATE TABLE TIPO_PESSOA (
	ID NUMERIC(8) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	FLG_MORADOR CHAR(1) NOT NULL,
	ATIVO CHAR(1) NOT NULL,
	CONSTRAINT PK_TIPO_PESSOA PRIMARY KEY (ID)
);

CREATE TABLE PESSOA (
	ID NUMERIC(8) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	
	RG VARCHAR(20) NULL,
	ORGAO_RG VARCHAR(10) NULL,
	CPF VARCHAR(11) NULL,
	CNH VARCHAR(20) NULL,
	
	CELULAR1 VARCHAR(12) NULL,
	CELULAR2 VARCHAR(12) NULL,
	FONE1 VARCHAR(12) NULL,
	FONE2 VARCHAR(12) NULL,
	ID_TIPO_PESSOA NUMERIC(8) NOT NULL,

	CEP NUMERIC(8) NULL,
	ENDERECO VARCHAR(200) NULL,
	BAIRRO VARCHAR(100) NULL,
	COMPLEMENTO VARCHAR(100) NULL,
	CIDADE VARCHAR(100) NULL,
	UF CHAR(2) NULL,
	OBSERVACOES TEXT NULL,
	FOTO TEXT NULL,
	
	CONSTRAINT PK_PESSOA PRIMARY KEY (ID),
	CONSTRAINT FK_PESSOA_TIPO FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TIPO_PESSOA (ID)
);

CREATE SEQUENCE SEQ_TIPO_PESSOA;
CREATE SEQUENCE SEQ_PESSOA;