CREATE TABLE PORTA (
	ID NUMERIC(8) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	ATIVO CHAR(1) DEFAULT 'A' NOT NULL,
	TIPO CHAR(1) NOT NULL,
	COMANDO VARCHAR(200),
	CONSTRAINT PK_PORTA PRIMARY KEY (ID)
);

CREATE TABLE AREA_COMUM (
	ID NUMERIC(8) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	ATIVO CHAR(1) DEFAULT 'A' NOT NULL,
	MAXIMO_CONVIDADOS NUMERIC(3),
	CONSTRAINT PK_AREA_COMUM PRIMARY KEY (ID)
);

CREATE TABLE PRE_LIBERACAO (
	ID NUMERIC(12) NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	DATA_LIBERACAO DATE,
	ID_MORADOR NUMERIC(8) NOT NULL,
	ID_PESSOA NUMERIC(8) NOT NULL,
	OBSERVACOES TEXT,
	CONSTRAINT PK_PRE_LIBERACAO PRIMARY KEY (ID),
	CONSTRAINT FK_PRE_LIBERACAO_MORADOR FOREIGN KEY (ID_MORADOR) REFERENCES MORADOR (ID),
	CONSTRAINT FK_PRE_LIBERACAO_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID)
);


-- DROP TABLE LIBERACAO

CREATE TABLE LIBERACAO (
	ID NUMERIC(12) NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	ID_USUARIO NUMERIC(8) NOT NULL,
	ID_PORTA NUMERIC(8) NOT NULL,
	TIPO_ACESSO CHAR(1) NOT NULL,
	ID_PRE_LIBERACAO NUMERIC(8),
	ID_MORADOR_AUTORIZACAO NUMERIC(8),
	TIPO_DESTINO CHAR(1) NOT NULL,
	ID_UNIDADE_DESTINO NUMERIC(8),
	ID_AREA_COMUM NUMERIC(8),
	FORMA_AUTORIZACAO NUMERIC(1),
	OBSERVACOES TEXT,
	FOTO TEXT,
	CONSTRAINT PK_LIBERACAO PRIMARY KEY (ID),
	CONSTRAINT FK_LIBERACAO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
	CONSTRAINT FK_LIBERACAO_PORTA FOREIGN KEY (ID_PORTA) REFERENCES PORTA (ID),
	CONSTRAINT FK_LIBERACAO_MORADOR FOREIGN KEY (ID_MORADOR_AUTORIZACAO) REFERENCES MORADOR (ID),
	CONSTRAINT FK_LIBERACAO_PRE_LIBERACAO FOREIGN KEY (ID_PRE_LIBERACAO) REFERENCES PRE_LIBERACAO (ID),
	CONSTRAINT FK_LIBERACAO_UNIDADE FOREIGN KEY (ID_UNIDADE_DESTINO) REFERENCES UNIDADE (ID),
	CONSTRAINT FK_LIBERACAO_AREA_COMUM FOREIGN KEY (ID_AREA_COMUM) REFERENCES AREA_COMUM (ID)
);

CREATE SEQUENCE SEQ_PORTA;
CREATE SEQUENCE SEQ_PRE_LIBERACAO;
CREATE SEQUENCE SEQ_LIBERACAO;
CREATE SEQUENCE SEQ_AREA_COMUM;

